services:
  postgres:
    image: postgres:15
    container_name: postgres_savage
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - battle
      - chat
      - characters
      - users

  users:
    build:
      context: ./UserService
      dockerfile: ../ServicesDocker/Dockerfile
    env_file:
      - .env
    expose:
      - "3001"
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  battle:
    build: 
      context: ./BattleService
      dockerfile: ../ServicesDocker/Dockerfile
    env_file:
      - .env
    expose:
      - "3002"
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  characters:
    build:
      context: ./CharacterService
      dockerfile: ../ServicesDocker/Dockerfile
    env_file:
      - .env
    expose:
      - "3003"
    ports:
      - "3003:3003"
    depends_on:
      - postgres

  chat:
    build:
      context: ./ChatService
      dockerfile: ../ServicesDocker/Dockerfile
    env_file:
      - .env
    expose:
      - "3004"
    ports:
      - "3004:3004"
    depends_on:
      - postgres