services:
  db:
    container_name: express-backend-db
    image: postgres:15
    restart: always
    shm_size: 128mb
    env_file:
      - ".env"
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql@15/data

volumes:
  pgdata:
    
