version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microservices_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  app-service:
    build: ./app-service
    container_name: app-service
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - /.env

  job-service:
    build: ./job-service
    container_name: job-service
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - /.env

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5002:5002"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - /.env

volumes:
  postgres_data:
