services:
  db:
    image: postgres:17
    container_name: backend_db
    restart: always
    env_file:
      - db.env
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
